steps:
  - name: node:16.18.0
    entrypoint: npm
    args: ["install"]
  - name: node:16.18.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'DB_BASE=${_DB_BASE}'
      - 'DB_DEV=${_DB_DEV}'
      - 'DB_PROD=${_DB_PROD}'
      - 'S3=${_S3}'
      - 'S3_IMAGES=${_S3_IMAGES}'
      - 'S3_AVATARS=${_S3_AVATARS}'
      - 'NODE_ENV=${_NODE_ENV}'
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "members-only-api",
           "--image", "gcr.io/cloudrun/members-only-api/members-only-api-image",
           "--platform", "managed",
           "--region", "us-central1",
           "--allow-unauthenticated"
    ]
timeout: "1600s"
